name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and Push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            <dockerhub-username>/ids706-miniproj12:latest
            <dockerhub-username>/ids706-miniproj12:${{ github.sha }}

      # Step 5: Verify the Docker image is pushed successfully
      - name: Verify Docker Image
        run: |
          echo "Docker image built and pushed to Docker Hub:"
          echo "  - latest"
          echo "  - ${{ github.sha }}"
